name: yutu
description: yutu

inputs:
  version:
    description: 'The version of the yutu binary to download'
    required: false
    default: ''
  token:
    description: 'The token to authenticate with the YouTube API'
    required: true
  command:
    description: 'The command to run, such as `video`, `channel` or `playlist`'
    required: false
    default: 'video'
  subcommand:
    description: 'The subcommand to run, such as `insert`, `update` or `list`'
    required: false
    default: ''
  flags:
    description: 'The flags to pass to the command'
    required: false
    default: ''

runs:
  using: composite
  steps:
    - uses: robinraju/release-downloader@v1.10
      with:
        repository: eat-pray-ai/yutu
        latest: ${{ inputs.version == '' }}
        tag: ${{ inputs.version }}
        fileName: yutu-linux-amd64
    - shell: bash
      run: |
        chmod +x yutu-linux-amd64
        echo ${{ inputs.token }} > ./youtube.token.json
        ./yutu-linux-amd64 ${{ inputs.command }} ${{ inputs.subcommand }} ${{ inputs.flags }}
