name: yutu
description: yutu

inputs:
  version:
    description: 'Version of the yutu binary to download'
    required: false
    default: ''
  credential:
    description: 'Credential to authenticate with the YouTube API'
    required: true
  token:
    description: 'Token to authenticate with the YouTube API'
    required: true
  command:
    description: 'Command to run, such as `video`, `channel` or `playlist`'
    required: false
    default: 'video'
  subcommand:
    description: 'Subcommand to run, such as `insert`, `update` or `list`'
    required: false
    default: ''
  flags:
    description: 'Flags passed to the command/subcommand'
    required: false
    default: ''

runs:
  using: composite
  steps:
    - uses: robinraju/release-downloader@v1.10
      with:
        repository: eat-pray-ai/yutu
        latest: ${{ inputs.version == '' }}
        tag: ${{ inputs.version }}
        fileName: yutu-linux-amd64
    - shell: bash
      run: |
        chmod +x yutu-linux-amd64
        echo ${{ inputs.credential }} > ./client_secret.json
        echo ${{ inputs.token }} > ./youtube.token.json
        ./yutu-linux-amd64 ${{ inputs.command }} ${{ inputs.subcommand }} ${{ inputs.flags }}
