name: Upload
description: Upload a video to YouTube

inputs:
  version:
    description: 'Version of the yutu binary to download'
    required: false
    default: ''
  credential:
    description: 'Credential to authenticate with the YouTube API'
    required: true
  token:
    description: 'Token to authenticate with the YouTube API'
    required: true
  flags:
    description: 'Flags passed to the command/subcommand'
    required: true

runs:
  using: composite
  steps:
    - uses: eat-pray-ai/yutu/actions/general@main
      with:
        version: ${{ inputs.version }}
        credential: ${{ inputs.credential }}
        token: ${{ inputs.token }}
        command: video
        subcommand: insert
        flags: ${{ inputs.flags }}
