name: Test

on:
  workflow_dispatch:
  push:
    paths:
      - 'cmd/**'
      - 'pkg/**'
      - 'go.mod'
      - 'main.go'
      - '.github/actions/test/**'
      - 'scripts/**'
  pull_request:
    paths:
      - 'cmd/**'
      - 'pkg/**'
      - 'go.mod'
      - 'main.go'
      - '.github/actions/test/**'
      - 'scripts/**'

jobs:
  test:
    runs-on: ubuntu-latest
    if: !startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod
      - uses: eat-pray-ai/yutu/.github/actions/test@main
