name: Test

on:
  workflow_dispatch:
  push:
    paths:
      - 'cmd/**'
      - 'pkg/**'
      - 'go.mod'
      - 'main.go'
      - '.github/actions/test/**'
  pull_request:
    paths:
      - 'cmd/**'
      - 'pkg/**'
      - 'go.mod'
      - 'main.go'
      - '.github/actions/test/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: eat-pray-ai/yutu/.github/actions/test@main
