name: Publish to WinGet
on:
  release:
    types:
      - published
jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: vedantmgoyal2009/winget-releaser@v2
        with:
          identifier: eat-pray-ai.yutu
          installers-regex: '\.exe$' # Only .exe files
          version: ${{ github.event.release.tag_name }}
          token: ${{ secrets.RELEASE_PAT }}
